import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import bcrypt from "npm:bcryptjs@2.4.3";

const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const supabase = createClient(supabaseUrl, serviceKey);
const allowedOrigins = new Set(["https://vattams.net", "https://www.vattams.net", "http://localhost:5173"]);
function corsHeaders(req: Request) { const origin = req.headers.get("Origin") ?? ""; return { "Access-Control-Allow-Origin": allowedOrigins.has(origin) ? origin : "https://vattams.net", "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey", "Vary": "Origin" }; }
function json(req: Request, data: Record<string, unknown>, status = 200) { return new Response(JSON.stringify(data), { status, headers: { ...corsHeaders(req), "Content-Type": "application/json", "Cache-Control": "no-store" } }); }
function error(req: Request, message: string, status = 400) { return json(req, { error: message }, status); }
async function sha256(value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join(""); }
function safeTutor(t: Record<string, unknown>) { return { id: t.id, employee_id: t.employee_id ?? null, full_name: t.full_name, email: t.email, phone: t.phone, city: t.city, state: t.state ?? null, highest_qualification: t.highest_qualification, subjects: t.subjects ?? [], exam_prep: t.exam_prep ?? [], teaching_mode: t.teaching_mode ?? null, availability: t.availability ?? null, status: t.status, approval_status: t.approval_status, payment_status: t.payment_status }; }
async function createSession(tutorId: string) { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); const token = Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join(""); const tokenHash = await sha256(token); const expires = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(); await supabase.from("tuition_tutor_sessions").delete().eq("tutor_id", tutorId).lt("expires_at", new Date().toISOString()); const { error: insertError } = await supabase.from("tuition_tutor_sessions").insert({ tutor_id: tutorId, token_hash: tokenHash, expires_at: expires }); if (insertError) throw new Error("Could not create tutor session."); return token; }
async function getTutorFromToken(token: string) { if (!token) return null; const tokenHash = await sha256(token); const { data: session } = await supabase.from("tuition_tutor_sessions").select("tutor_id, expires_at").eq("token_hash", tokenHash).gt("expires_at", new Date().toISOString()).maybeSingle(); if (!session) return null; const { data: tutor } = await supabase.from("tuition_tutors").select("id, employee_id, full_name, email, phone, city, state, highest_qualification, subjects, exam_prep, teaching_mode, availability, status, approval_status, payment_status").eq("id", session.tutor_id).maybeSingle(); if (!tutor || tutor.status !== "approved" || tutor.approval_status !== "APPROVED") return null; return tutor; }
Deno.serve(async (req: Request) => { if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders(req) }); if (req.method !== "POST") return error(req, "Method not allowed", 405); try { const body = await req.json(); const action = body?.action;
  if (action === "login") { const email = String(body?.email ?? "").trim().toLowerCase(); const password = String(body?.password ?? ""); if (!email || !password) return error(req, "Email and password are required."); const { data: tutor } = await supabase.from("tuition_tutors").select("id, employee_id, full_name, email, phone, city, state, highest_qualification, subjects, exam_prep, teaching_mode, availability, status, approval_status, payment_status, password_hash").eq("email", email).maybeSingle(); if (!tutor || !tutor.password_hash) return error(req, "Invalid email or password.", 401); if (tutor.status !== "approved" || tutor.approval_status !== "APPROVED") return error(req, "Your tutor account is not approved yet.", 403); if (!(await bcrypt.compare(password, tutor.password_hash))) return error(req, "Invalid email or password.", 401); const token = await createSession(tutor.id); return json(req, { success: true, token, tutor: safeTutor(tutor) }); }
  if (action === "me") { const tutor = await getTutorFromToken(String(body?.token ?? "")); if (!tutor) return error(req, "Your tutor session has expired. Please sign in again.", 401); return json(req, { success: true, tutor: safeTutor(tutor) }); }
  if (action === "logout") { const token = String(body?.token ?? ""); if (token) await supabase.from("tuition_tutor_sessions").delete().eq("token_hash", await sha256(token)); return json(req, { success: true }); }
  return error(req, "Unknown action.");
} catch (err) { console.error("[tuition-tutor-auth]", err); return error(req, err instanceof Error ? err.message : "Unexpected error.", 500); } });
